### ISSUE TITLE
Crashing with "Converting circular structure to JSON"

### ISSUE THREAD

**Issue by harpocrates** [scala-steward-org/scala-steward-action#104]
I'm trying out `scala-steward-action` on one of my private personal projects and following the README with the default configuration doesn't appear to be working.

### Contents of `.github/workflows/scala-steward.yml`

```
# This workflow will launch at 00:00 every Sunday
on:
  schedule:
    - cron: '0 0 * * 0'
  repository_dispatch:
    types: [scala-steward]

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.SCALA_STEWARD }}
```

### Github Actions output

```
> Launch Scala Steward
Run scala-steward-org/scala-steward-action@v2
  with:
    github-token: ***
    scala-steward-version: 0.6.0
    ignore-opts-files: true
    sign-commits: false
✓ Connected to Maven Central
✓ Coursier installed, version: 2.0.0-RC6-23
✓ Github Token provided as input
✓ Github Repository set to: harpocrates/hermes-ci
##[error] ✕ Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
```

That error seems to be coming from some failing `JSON.stringify`, which makes me think the issue is somewhere is the typescript/JS of the action and not in Scala Steward.
