### ISSUE TITLE
Unable to retrieve user information from Github

### ISSUE THREAD

**Issue by tusharmath** [scala-steward-org/scala-steward-action#173]
I am unable to figure out what this issue is about. This is for a repository that is inside a GitHub enterprise account.

**Config**
```yml
name: Scala Steward
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

<img width="592" alt="Screenshot 2020-10-10 at 1 01 27 AM" src="https://user-images.githubusercontent.com/194482/95624216-2230e780-0a94-11eb-9e2c-44bcb95a80fb.png">

**Comment by alejandrohdezma** [comment]
Hey @tusharmath thanks for opening this. I believe this was caused because `https://api.github.com` was used as the `--vcs-api-host` param (instead of your Github Enterprise one). I just created & merged #174 to fix this. Can you try to run the action again and add the `github-api-url` input? Thanks!

```yaml
name: Scala Steward
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-api-url: 'https://git.yourcompany.com/api/v3'
```

**Comment by tusharmath** [comment]
Tried again, similar error. 

<img width="1451" alt="Screenshot 2020-10-11 at 12 53 55 PM" src="https://user-images.githubusercontent.com/194482/95672726-d92a8180-0bc0-11eb-9352-2a1157c87f2f.png">

**Comment by alejandrohdezma** [comment]
Can you enable the [Step Debug Logs](https://github.com/actions/toolkit/blob/main/docs/action-debugging.md#how-to-access-step-debug-logs), we should see then the error that is happening. Just add a new secret named `ACTIONS_STEP_DEBUG` and set its value to `true`.

BTW I just found out that Github [adds an environment variable `GITHUB_API_URL`](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables). Could you tried to set the input as: `github-api-url: ${{ env.GITHUB_API_URL }}` and see if it uses the correct URL?

**Comment by tusharmath** [comment]
Enabled debugging —

<img width="773" alt="Screenshot 2020-10-11 at 2 04 45 PM" src="https://user-images.githubusercontent.com/194482/95673968-ba30ed00-0bca-11eb-93ca-e633d2103a98.png">

**Comment by alejandrohdezma** [comment]
🤔 I've seen that error in the past when using a Personal Access Token without enough permissions. Can you check if that's the case? Also I don't see the `github-api-url` input in the input list.

**Comment by tusharmath** [comment]
@alejandrohdezma thanks for helping me debug the issue 🙏

I don't use a personal access token, for the enterprise account. Might have to check with the IT team 🙄

This is the new config, I keep getting "Invalid workflow file" error.

```yml
name: Scala Steward
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

inputs:
  github-api-url: ${{ env.GITHUB_API_URL }}

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward

    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}


```

Is this not the right

**Comment by alejandrohdezma** [comment]
On one hand, the action is intended to be used with a Personal Access Token (instead of the provided `GITHUB_TOKEN`) so you should try to create one and add it as `github-token`.

On the other hand, the `github-api-url` input should be under `jobs.scala-steward.steps.with` like:


```yaml
name: Scala Steward
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:  

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward

    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-api-url: ${{ env.GITHUB_API_URL }}
```
