### ISSUE TITLE
Unable to find author's email. Either ensure that the token's Github Account has the email privacy feature disabled for at least one email or use the `author-email` input to provide one.

### ISSUE THREAD

**Issue by meldmy** [scala-steward-org/scala-steward-action#175]
Hi, I got the following error:

>  ✕ Unable to find author's email. Either ensure that the token's Github Account has the email privacy feature disabled for at least one email or use the `author-email` input to provide one.

This is [my workflow](https://github.com/meldmy/draft-scala-pet-project/blob/master/.github/workflows/scala-steward.yml): 

#
on:
  schedule:
    - cron: '* * * * *'

```
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          github-repository: meldmy/draft-scala-pet-project
```

In the readme, I found that I don't need to add my mail to configuration.
Can you assist me with it, please? 🙏🏻
