### ISSUE TITLE
Can't find repos.md

### ISSUE THREAD

**Issue by bilal-fazlani** [scala-steward-org/scala-steward-action#227]
```yml
# This workflow will launch at 00:00 every Sunday
name: ScalaSteward

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          repos-file: 'repos.md'
          author-email: ${{ secrets.EMAIL }}

```

```
Error:  ✕ The path indicated in `repos-file` (repos.md) does not exist
```

repo link:
https://github.com/bilal-fazlani/scala-steward-repo
