### ISSUE TITLE
[FEATURE REQUEST] Assign PRs automtically

### ISSUE THREAD

**Issue by herzrasen** [scala-steward-org/scala-steward-action#291]
It would be great to be able to assign the PRs created by Scala Steward to one or more reviewers automatically. 

What do you think?

**Comment by alejandrohdezma** [comment]
Hi! This is something already possible by using external GitHub Actions like [this one](https://github.com/kentaro-m/auto-assign-action), and with way more features that we could add here. It is something I already do in my PRs:

https://github.com/alejandrohdezma/sbt-ci/blob/f02e72781afda5b2c29bb38d5a36de66d5ff22fc/.github/workflows/ci.yml#L94-L103

<img width="465" alt="Screenshot 2021-10-19 at 11 34 02" src="https://user-images.githubusercontent.com/9027541/137883664-3e188169-2197-4f12-ad75-8639173b936e.png">

In that ☝🏼 example I check the existance of a `.github/auto_assign.yml` because I share the same workflows accross many repos but you could just do the following:

```yaml
# .github/workflows/add_review.yml

name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'your-steward-bot'
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.0
```

With a simple config like:

```yaml
# .github/auto_assign.yml

addReviewers: true
reviewers:
  - reviewerA
  - reviewerB
  - reviewerC
```
