### ISSUE TITLE
Scala-steward execution hangs at refresh cache of target repo

### ISSUE THREAD

**Issue by spliakos** [scala-steward-org/scala-steward-action#294]
When I try to run scala-steward against another repo, GHA execution always hangs at the following spot. I have seen a similar closed issue, where there is a problem with cache in self-hosted runners, but this is happening even though the runner is not self hosted. Action logs are as follows:

✓ Coursier installed, version: 2.0.16
✓ Github Token provided as input
✓ User information retrieved from Github
✓ Github Repository set to: myreponame.
✓ Scala Steward workspace created
✓ scalafmt installed, version: scalafmt 3.0.7
Launching org.scala-steward:scala-steward-core_2.13:0.12.0
  2021-10-27 09:43:12,963 INFO   
    ____            _         ____  _                             _
   / ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
   \___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
    ___) | (_| (_| | | (_| |  ___) | ||  __/\ V  V / (_| | | | (_| |
   |____/ \___\__,_|_|\__,_| |____/ \__\___| \_/\_/ \__,_|_|  \__,_|
   v0.12.0
   
  2021-10-27 09:43:14,661 INFO  Loaded 43 artifact migrations
  2021-10-27 09:43:15,063 INFO  Loaded 24 Scalafix migrations
  2021-10-27 09:43:15,558 INFO  Run self checks
  2021-10-27 09:43:15,573 INFO  Using git version 2.33.1
  2021-10-27 09:43:16,821 INFO  Using scalafmt 3.0.7
  2021-10-27 09:43:17,770 INFO  Clean workspace /home/runner/scala-steward/workspace
  2021-10-27 09:43:17,781 INFO  Add global sbt plugins
  2021-10-27 09:43:17,883 INFO  ──────────── Steward myreponame ────────────
  2021-10-27 09:43:17,885 INFO  Check cache of myreponame
  2021-10-27 09:43:18,566 INFO  Clone myreponame
  2021-10-27 09:43:24,331 INFO  Refresh cache of myreponame

and from here on, it keeps on running indefinitely, without any progress. I need to cancel the runner for the Action to stop. When I don't set github-repository then it's running against the repo where scala-steward action is installed, and it's working, but when target is different repo, it hangs. Here is my workflow file:

```
jobs:
  scala-steward:
    name: scala-steward
    runs-on: ubuntu-latest
    steps:
      # This is necessary to ensure that the most up-to-date version of
      # REPOSITORIES.md is used.
      - uses: actions/checkout@v2.3.4
        with:
          ref: main
          fetch-depth: 0
      - name: Execute Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          # A GitHub personal access token tied to a user that will create
          # pull requests against your projects to update dependencies. More
          # on this under the YAML snippet.
          github-token: ${{ secrets.AWSINFRA_PAT }}
          # A Markdown file with a literal Markdown list of repositories
          # Scala Steward should monitor.
          github-repository: myreponame
          #repos-file: REPOSITORIES.md
          author-email: scala-steward@dinotech.com
          author-name: Scala Steward
          cache-ttl: 0s
```
