### ISSUE TITLE
Option for single / combined PR with all updates

### ISSUE THREAD

**Issue by EwoutH** [scala-steward-org/scala-steward-action#304]
It would be great to have an option for the Scala Steward to open a single pull request combining all the updates. In some cases this can be useful to prevents a flood of PRs and ensure compatibility between the dependencies using a projects CI.

**Comment by alejandrohdezma** [comment]
Hey @EwoutH, thanks for the suggestion, although I believe this would be a feature request for the Scala Steward itself, not the action, given that the action uses Scala Steward under the hood and doesn't do anything that Scala Steward can't.

**Comment by alejandrohdezma** [comment]
Also it is something you can already "partially" do by using a custom branch to make the updates:

1. Set Scala Steward to update a `develop` branch instead of the default one.
2. Scala Steward PRs can be auto-merged into that branch.
3. Every so often create a PR from the `develop` branch into the default one (this is a step that can be easily performed usign GH actions `schedule`).

```yaml
name: Create Scala Steward Updates PR

on:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  create-scala-steward-dependency-updates-pull-request:
    name: Create PR from `develop` to `main`
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "develop",
              base: "main",
              title: "Scala Steward dependency updates"
            })
```
