### ISSUE TITLE
Caching causes errors when running scala steward after revoking access

### ISSUE THREAD

**Issue by lordqwerty** [scala-steward-org/scala-steward-action#321]
## 🗒️ Description
Caching the `repos.md` file causes build fails when access to a repo listed in `repos.md` is lost. The exact options I am using for Scala Steward Action are:

```yaml
- name: Execute Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.17.0
        timeout-minutes: 1440
        with:
          author-email: EMAIL
          author-name: USER
          sign-commits: true
          signing-key: KEY_ID
          github-token: APP_INSTALL_TOKEN
          github-app-id: APP_ID
          github-app-key: APP_PRIVATE_KEY
          cache-ttl: 0s

          # Scala Steward running configs
          timeout: 24hours
          ignore-opts-files: false
```

Since I am using an [Installation Token](https://docs.github.com/en/rest/reference/apps#create-an-installation-access-token-for-an-app) specifying `repositories` in the body, I scope down the access to a subset of repos granted access by the GitHub app. This means that in a different run of the action where access is not given to a repository that is now cached, it correctly 404s and the action fails.

Looking at the code I can see that `repos.md` is cached, since only the following items are removed:
https://github.com/scala-steward-org/scala-steward-action/blob/b344195cb82c8524bddebc9286b5869150b1f0ac/src/workspace.ts#L63-L65

This means that when the action cache is restored it will use the contents of `repo.md` always? I think the `cache-ttl` setting it to `0s` initially stopped this from happening but PR https://github.com/scala-steward-org/scala-steward-action/pull/316 I think change the behaviour?

## ⚠️ Problem

To illustrate the above issue on a more high-level. I have the following things:
- A GitHub app that grants READ|WRITE access to code and PRs via an Installation Token
- 3 Scala repositories that we will call Repo A, Repo B, Repo C
- A GitHub action that uses the Scala Steward Action

I then do the following:

1. I run the Scala Steward action on A, using an Installation Token just for repo A. It succeeds and opens PRs as expected.

2. I then run the Scala Steward action on B, using an Installation Token just for repo B.
  a. It executes Scala Steward for repo B and finds outdated dependencies, but at this point no PRs have been opened.
  b. Since Scala Steward loaded from cache, it then tries to access repo A using an installation token for repo B and causes a 404. 
  c. This then results in no PRs opening and the action failing.

3. I then run Scala Steward on B, using an Installation Token just for repo C. It fails as above but also tries to access repos A and B since they are in the cache. 

4. I then run Scala Steward on A, using an Installation Token just for repo A. It fails as above but also tries to access repos B and C since they are in the cache. 

## ❓  Possible solution
Could `repos.md` be removed from the cache, since this can quickly and easily be re-generated? Or is it needed for other reasons? 

Please let me know how I can help, I would love to help getting this solved 🙏 
If I have misunderstood something please let me know where I'm going wrong 🙇

**Comment by alek-w** [comment]
@exoego @alejandrohdezma 
wdyt?

**Comment by alejandrohdezma** [comment]
👋🏼 I didn't know about this "feature" when using the GitHub App mode. Unfortunately I don't have enough knowledge on the impact of removing that file from the cache. @fthomas is it safe to remove it as we do with the `repos` or `store/refres_error` folders?

**Comment by fthomas** [comment]
I think it is safe to remove the `repos.md` file if it is recreated on the next run.

**Comment by alejandrohdezma** [comment]
Taking a closer look I don't understand how this is happening. We are caching the `workspace` folder [here](https://github.com/scala-steward-org/scala-steward-action/blob/712c1d3e53ac0740ff2189e4589fce40e82f0350/src/workspace.ts?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L70), but that folder does not include the `repos.md` file (created in its parent folder). @lordqwerty my understanding is that you are adding repositories to the installation on your 1, 2, 3, 4 steps?

**Comment by lordqwerty** [comment]
Yep so I have the app installed in each repo that will generate tokens for use by Scala Steward that I can control the scope of. I then use a token in a run of the scala steward action.

Please note: I have 1 repo that contains a number of workflow files and config for running scala steward. One workflow file could run scala steward on one or more repos depending on the contents of `REPOSITORIES.md` as defined by a developer.  Each workflow can then be either manually triggered or executed on a schedule. There is a reason behind this design choice. So the repo layout looks a little like this:

```
├── .github
│   └── workflows
│       ├── repoA.yml
│       ├── repoBandC.yml
├── .gitignore
├── README.md
├── repoA
│   ├── .scala-steward.conf
│   └── REPOSITORIES.md
├── repoBandC
│   ├── .scala-steward.conf
│   └── REPOSITORIES.md
└── template
    ├── .scala-steward.conf
    ├── README.md
    ├── REPOSITORIES.md
    └── project-action.yml
```

As a sanity check, I am running on a public runner (`ubuntu-latest`) to verify if it might be an issue with caching.

**Comment by alejandrohdezma** [comment]
So you are using both the `repos-file` and the `github-app-id` inputs?

**Comment by lordqwerty** [comment]
So this isn't a caching issue. This was my mistake and thank you everyone for looking at this 🙇 

The issue here is how I used the GitHub API to generate a token that limits the repos it has access to. This in combination with specifying the inputs `github-app-id` and `github-app-key` proved to be lethal and sent me down a cache rabbit hole.

See the following bit of the README:
https://github.com/scala-steward-org/scala-steward-action/blob/712c1d3e53ac0740ff2189e4589fce40e82f0350/README.md#L201-L220 

In this case Scala Steward was listing the repositories using the app, since it has access to the private key. But it then uses the token to access the repos; and because I limit how a token is generated this causes the 404s even when specifying the `REPOSITORIES.md` file as input. 

So the solution for me was to remove the `github-app-id` and `github-app-key` action inputs, and just use the `github-token` input. My use case was weird in this sense since I want to use a GitHub app but not grant access to all my repos.

### 🐛 Possible bugs

1. Specifying `github-app-id` and `github-app-key` inputs ignores the repos listed in `REPOSITORIES.md`, and assumes the `github-token` input has access to all repos in my testing. Perhaps documentation update? Or my use case is niche.

2. The GitHub app key is not cleaned from the workspace. 
  a. See the creation here: https://github.com/scala-steward-org/scala-steward-action/blob/712c1d3e53ac0740ff2189e4589fce40e82f0350/src/check.ts#L154
  b. I can't see it being cleaned in:
  https://github.com/scala-steward-org/scala-steward-action/blob/712c1d3e53ac0740ff2189e4589fce40e82f0350/src/workspace.ts#L63-L65

Happy for the issue to be closed if no further discussion is required 😃

**Comment by alejandrohdezma** [comment]
I do something similar for my personal repositories (although I don't change between installation tokens). But one alternative you could try is to get the installation token, then create the `repos.md` file programmatically and don't use the `github-app-*` inputs. Something like:

```yaml
run-scala-steward-all-repos:
  name: Run Scala Steward in all the repositories managed by the GitHub App
  runs-on: ubuntu-latest
  steps:
    - name: Get token
       id: get_token
       uses: microsoftgraph/get-app-token@main
       with:
         application-id: ${{ secrets.APPLICATION_ID }}
         application-private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

    - name: Create `repos.md`
       run: gh api installation/repositories |  jq -r '.repositories | map(.full_name) | .[] | "- " + .' > 'repos.md'
       env:
         GITHUB_TOKEN: ${{ steps.get_token.outputs.app-token }}

    - name: Launch Scala Steward on all repositories managed by the Github App
       uses: scala-steward-org/scala-steward-action@v2
       with:
         github-token: ${{ steps.get_token.outputs.app-token }}
         author-email: bot_id+app_name[bot]@users.noreply.github.com
         author-name: app_name[bot]
         repos-file: repos.md
```
