### ISSUE TITLE
General question: does Scala-steward-action pick up new versions of private libraries?

### ISSUE THREAD

**Issue by lonesai** [scala-steward-org/scala-steward-action#337]
More context: if I updated the version of my own library would scala-steward-action be able to pick it up? given the projects are under GitHub enterprise. 
Thanks in advance!

**Comment by alejandrohdezma** [comment]
Hi @lonesai 👋🏼 

Where are you publishing those libraries? GitHub Packages?

**Comment by lonesai** [comment]
> Hi @lonesai 👋🏼
> 
> Where are you publishing those libraries? GitHub Packages?

yup GitHup Packages

**Comment by alejandrohdezma** [comment]
You'll need to add the following before running Scala Steward like you'll do in any other installation:

```yaml
- name: Add SBT credentials for Artifactory
  env:
    ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
    ARTIFACTORY_PWD: ${{ secrets.ARTIFACTORY_PWD }}
  run: |
     mkdir -p ~/.sbt/1.0
     echo 'credentials += Credentials("Artifactory", "your-artifactory-url", "'$ARTIFACTORY_USER'", "'$ARTIFACTORY_PWD'")' > ~/.sbt/1.0/credentials.sbt
     cat > ~/.sbt/repositories <<EOF
     [repositories]
       local
       ivy-releases: your-artifactory-url/artifactory/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
       libs-release: your-artifactory-url/artifactory/libs-release/
       maven-central
     EOF
```
