### ISSUE TITLE
pre script fails on runners without pre-installed JVM

### ISSUE THREAD

**Issue by ybasket** [scala-steward-org/scala-steward-action#440]
It seems like #427 broke running Scala Steward on runners where no JVM is pre-installed, but only installed during the job itself, like in this workflow:

```yaml
jobs:
  scala-steward:
    runs-on: [self-hosted, dev]
    name: Launch Scala Steward
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_BOT_PAT }}
      - name: Setup JDK & Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: temurin@17
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          ...
```

Is there a way to opt-out of having `pre` requiring `coursier` already or could one reasonably be added? I see no (easy) way to run something before that `pre` script and the runners are shared across an enterprise, getting a JVM installed there has some drawbacks.
