### ISSUE TITLE
Fails with `Error:  ✕ Not Found`

### ISSUE THREAD

**Issue by guizmaii** [scala-steward-org/scala-steward-action#522]
Here's my config:
```yaml
name: Scala Steward

# This workflow will launch everyday at 00:00
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  scala-steward:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.59.0
        with:
          github-app-id: ${{ secrets.SCALA_STEWARD_APP_ID }}
          github-app-installation-id: ${{ secrets.SCALA_STEWARD_APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
```

And here's the error:
![image](https://github.com/scala-steward-org/scala-steward-action/assets/1193670/a84aaa05-902b-4241-99b9-a2d4d877cf07)
