### ISSUE TITLE
Signing commits 

### ISSUE THREAD

**Issue by nmcb** [scala-steward-org/scala-steward-action#578]
Disclaimer: This issue may very well be a newbie question that warrant's an RTFM response. If so please point me to the documentation as I really can't find a solution on how to configure the action's workflow such that PRs created by the action are signed by my GPG key as configured in GH.

I'm having the action installed as a GH Application on my user account as:

<img width="487" alt="Screenshot 2024-03-01 at 09 42 43" src="https://github.com/scala-steward-org/scala-steward-action/assets/1698211/c0d3fe69-4d38-4182-9575-53aa57ea1550">

And created a separate repository that runs the action daily with workflow:

```yaml
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

name: Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-app-id: ${{ secrets.SCALA_STEWARD_APP_ID }}
          github-app-installation-id: ${{ secrets.SCALA_STEWARD_APP_II }}
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PK }}
          author-name: 'nmcb'
          author-email: 'nmcb@xs4all.nl'
          sign-commits: true
          signing-key: '11CE225DB8EE6401'
```

In which the signing key refers to the ID of the GPG key with which I sign commits, this key is registered in my GH account as:

<img width="967" alt="Screenshot 2024-03-01 at 09 49 14" src="https://github.com/scala-steward-org/scala-steward-action/assets/1698211/96375a82-177b-40c2-82c3-3c1ed657af12">

Running the action (which triggers an update on one of my repositories requiring and thus creating a PR) shows the following error:

```
2024-03-01 08:35:46,832 ERROR Steward nmcb/nmcb-automation failed
  org.scalasteward.core.io.process$ProcessFailedException: 'GIT_ASKPASS=/home/runner/scala-steward/askpass.sh "SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" git -c core.hooksPath=/dev/null commit --all --gpg-sign -m Update scala3-library to 3.3.3' exited with code 128.
  error: gpg failed to sign the data:
  gpg: directory '/home/runner/.gnupg' created
  gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
  gpg: skipped "11CE225DB8EE6401": No secret key
  [GNUPG:] INV_SGNR 9 11CE225DB8EE6401
  [GNUPG:] FAILURE sign 17
  gpg: signing failed: No secret key
  fatal: failed to write commit object
  	at org.scalasteward.core.io.process$.$anonfun$slurp$7(process.scala:78)
  	at org.scalasteward.core.io.process$.$anonfun$slurp$7$adapted(process.scala:72)
  	at flatMap @ org.scalasteward.core.io.process$.$anonfun$slurp$5(process.scala:72)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at modify @ fs2.internal.Scope.close(Scope.scala:262)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
  	at get @ fs2.internal.Scope.openScope(Scope.scala:275)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1215)
  	at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
```

What am I missing ?
