### ISSUE TITLE
Document that an application is not required

### ISSUE THREAD

**Issue by SpecialThing44** [scala-steward-org/scala-steward-action#617]
https://github.com/scala-steward-org/scala-steward-action/blob/cc64e5c8ef79944b4c705c83f84a759108b1049e/README.md?plain=1#L18 This is inaccurate. I have successfully ran this action without one, which is demonstrated in https://github.com/SpecialThing44/scala-steward-action-test.

If you remove the below lines from the workflow file:
```yml
with:
  github-app-id: ${{ secrets.APP_ID }}
  github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
  github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
```
Add write permissions as such at the top level:
```yml
permissions:
  contents: write
  pull-requests: write
```
and ensure that GitHub Actions has permissions to create and approve pull requests:
At <username>/<repo_name>/settings/actions for users
At <organization>/<organization_name>/settings/actions for organizations.

Then you can use this action without having to create an app or any related secrets.

In general this is nice because it saves a lot of time, and avoids having to maintain secrets and apps with permissions.

As an added bonus, it works in forks.
